### ISSUE TITLE
upgrade: Upgrade Smart Contracts to Cairo 1 and Update Flex Marketplace Deployment Steps

### ISSUE THREAD

**Issue by and1vo** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#1]
### Description
We need to upgrade our smart contracts from Cairo 0 to Cairo 1. This upgrade is essential to stay up-to-date with the latest features and improvements in the Cairo language.

### Contracts to Upgrade
The following smart contracts need to be reviewed and upgraded:

- [x] #4 
- [x] #5
- [x] #7
- [x] #8
- [x] #9
- [x] #10 
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x] #15

### Deployment Steps
Here are the steps to deploy the Flex Marketplace after the upgrade:
1. Deploy Proxy
2. Deploy CurrencyManager and whitelist ETH
3. Deploy StrategyStandardSaleForFixedPrice
4. Deploy ExecutionManager and whitelist StrategyStandardSaleForFixedPrice
5. Deploy RoyaltyFeeRegistry
6. Deploy RoyaltyFeeManager
7. Deploy SignatureChecker2
8. Deploy Marketplace
9. Deploy TransferManagerERC721
10. Deploy TransferManagerERC1155
11. Deploy TransferSelectorNFT
12. Setup the Marketplace contract: Ensure to set TransferSelectorNFT before usage.

### Contributors
Calling on contributors to assist with this upgrade. Please review each contract, update the code to Cairo 1, and test thoroughly.

**Comment by Mohiiit** [comment]
Hey, I want to contribute. Where can I start from?

**Comment by ametel01** [comment]
@and1vo happy to contribute, i can start by initializing a new scarb project inside the repo and write all the functions headers for the contracts, this way will be easier for contributors to join

**Comment by Mohiiit** [comment]
Hey @ametel01, would love to collaborate and contribute on this.

**Comment by and1vo** [comment]
> Hey @ametel01, would love to collaborate and contribute on this.

> @and1vo happy to contribute, i can start by initializing a new scarb project inside the repo and write all the functions headers for the contracts, this way will be easier for contributors to join

Greatings @Mohiiit @ametel01 , happy to have you guys as contributors for Flex, we'll annouce the grants for this issue in the next few days! Buckle up!

**Comment by VictorONN** [comment]
Hello, would love to help out

**Comment by and1vo** [comment]
> Hello, would love to help out

Welcome @VictorONN , let's pick a contract and make it cairo1 compatible and get paid while doing it!!!

**Comment by ametel01** [comment]
@and1vo i propose to create a a separate issue for each contract and assign them to contributors to avoid overlapped pr and make easier for people to join, I can do that if that's ok

**Comment by and1vo** [comment]
> @and1vo i propose to create a a separate issue for each contract and assign them to contributors to avoid overlapped pr and make easier for people to join, I can do that if that's ok

really appreciate that, I'm happy to merge asap!!!

**Comment by ametel01** [comment]
Also if you can wait for mainnet upgrade to deploy I think we should use 2.4.0 compiler rather than 2.3.1.

**Comment by and1vo** [comment]
> Also if you can wait for mainnet upgrade to deploy I think we should use 2.4.0 compiler rather than 2.3.1.

I don't have the upgrade schedule for mainnet, so I'm thinking if 2.4.0 is not much different from 2.3.1, then we can start at 2.3.1 to be mainnet compatible then we'll upgrade to 2.4.0. What do you think!

**Comment by ametel01** [comment]
This is from the Starknet forum:
```
These are the planned dates for the networks’ upgrades:

Nov 19, 2023: V0.12.3 Goerli testnet
Dec 12, 2023: V0.13.0 Goerli testnet and Sepolia testnet.
Dec 19, 2023: V0.12.3 mainnet.
Jan 10, 2024: V0.13.0 mainnet, pending governance vote.
```
Ideally we should just use 2.4.0 to avoid code refactor but If you think we can get the contract written and tested before Jan 10 we should go with 2.3.1 and the refacto.

**Comment by and1vo** [comment]
> This is from the Starknet forum:
> 
> ```
> These are the planned dates for the networks’ upgrades:
> 
> Nov 19, 2023: V0.12.3 Goerli testnet
> Dec 12, 2023: V0.13.0 Goerli testnet and Sepolia testnet.
> Dec 19, 2023: V0.12.3 mainnet.
> Jan 10, 2024: V0.13.0 mainnet, pending governance vote.
> ```
> 
> Ideally we should just use 2.4.0 to avoid code refactor but If you think we can get the contract written and tested before Jan 10 we should go with 2.3.1 and the refacto.

Thanks for the information, on second thought, 2.4.0 would be the best tho!

**Comment by Mohiiit** [comment]
Hey @ametel01, where can I start from?
