### ISSUE TITLE
Implement Functions' Body for RoyaltyFeeManager contract

### ISSUE THREAD

**Issue by ametel01** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#10]
Implement the functions' body for the [RoyaltyFeeManager](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/flex_marketplace/src/marketplace/royalty_fee_manager.cairo) contract. For reference and consistency, the implementation should align with the existing Cairo0 [`RoyaltyFeeManager.cairo`](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/contracts/marketplace/RoyaltyFeeManager.cairo) contract.

Dependencies:

scarb v2.4.0
snforge 0.13.0

Requirements:

Ensure that the code passes both `scarb fmt` and `scarb build` commands without errors, ensuring proper formatting and successful build.

**Comment by AniDhumal** [comment]
Can I take this?

**Comment by and1vo** [comment]
> Can I take this?

Assigning this to you @AniDhumal ~
