### ISSUE TITLE
test: Write unit tests for Flex Haus Collectible

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#116]
Complete the unit test of `flex_haus/src/collectible/FlexHausCollectible.cairo`, write test cases in `flex_haus/tests` folder.

Use scarb test to run all the tests.

All test cases are required to PASS.

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a web3 developer, I have expertise in smart contracts, decentralized technologies, and frameworks like React. I can build innovative dApps, contribute to open-source projects, educate others, and network with industry leaders to advance my career in the decentralized space.

### How I plan on tackling this issue
I will complete the unit tests for `FlexHausCollectible.cairo` in the `flex_haus/src/collectible/` directory by writing test cases in the `flex_haus/tests` folder. I will use `scarb test` to run all the tests and ensure they pass successfully.

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a frontend web 3 developer I have contributed to this repository in the last OD Hack and would love to continue in that same trajectory with over 55 + contribution

### How I plan on tackling this issue
within an ETA of 48 hours

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Mid level Cairo Developer

### How I plan on tackling this issue
I will write test cases that cover all the key functions of the contract and ensure the tests verify the expected behavior for both success and failure scenarios and also include ownership checks, factory validation, and handling of the reentrancy guard.

**Comment by jedstroke** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a seasoned fullstack web3 developer.  Here's my lil' portfolio: https://www.jedshock.com

### How I plan on tackling this issue
My ETA: 30 hours 
I can take on this issue

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer. I will love to solve this issue. Its something I can handle

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute to this project please ser. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo. I'm very good at testing.

### How I plan on tackling this issue
To solve this issue, I'll take the following steps:
1. I'll first of all have to understand the FlexHausCollectible.cairo Contract. So I'll read thoroughly  to understand the code inside flex_haus/src/collectible/FlexHausCollectible.cairo. I'll also iIdentify key functionalities, including the methods and logic implemented in the contract, such as minting, transferring collectibles, querying information.
2. I'll ensure I have Scarb installed, which is the tool that I will use to compile and run the tests.
3. I'll write unit tests(I'll create a new test file in the flex_haus/tests folder) that will cover all public methods and core functionality of the contract.
4. Then I'll use the scarb test command to run all test cases.
5. Lastly, I'll test to ensure that every function in the contract has been tested.

Please assign me, I'm ready to work.

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
My name is Blessing, i am a frontend developer and a web3 developer.

### How I plan on tackling this issue
To effectively resolve this issue, i would start by 
 interpreting any error messages from scarb test to figure out if it's a syntax issue, function mismatch, or logic error.

Fix Function Signatures: If there's a mismatch between the contract functions and test cases, I will help you align the function parameters correctly.

Check Constructor/Deployment: I will guide you to ensure the constructor and contract deployment in the tests are done correctly.

Balance and Transfer Issues: If there are errors with token balances or transfers, I will help debug and confirm the logic works as expected.

Event Emission: I will assist in ensuring events are emitted properly and guide you on how to verify this in tests.

Run Tests and Debug: I will help you run scarb test, interpret the results, and make necessary adjustments until all tests pass.

By following this approach , i aim to provide a realiable and efficient solution to make all the cases to pass

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
hello i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience. I'm also a member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies.

### How I plan on tackling this issue
To solve this, I will:
1. Analyze the contract functionality.
2. Create a setup function to deploy the contract and initialize any necessary values for the test.
3. Develop the unit tests to cover the contract functionalities.
4. Verify that everything is working and document the code.

**Comment by No-bodyq** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a full-stack and block chain dev with experience in writing tests for smart contracts using cairo. Here is my Only dust profile: https://app.onlydust.com/u/No-bodyq.

### How I plan on tackling this issue
I will inspect the FlexHaus file to get accustomed to the functions and their expected behavior then i will write unit tests for each function comparing the output with expected values and taking into account different edge cases

**Comment by coxmars** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hi @0xandee, I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working on ByteBeasts, a fully on-chain RPG game built using the Dojo Engine framework.

### How I plan on tackling this issue
- I’ll start by reviewing the FlexHausCollectible.cairo file to understand the core functionality and identify all the test cases needed.
- Then, I’ll write unit tests for the key scenarios in the flex_haus/tests folder, covering both expected outcomes and edge cases.
- I’ll use scarb test to ensure all tests pass and make any adjustments needed to get full coverage.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a frontend developer with experience in writing smart contracts using cairo and solidity

### How I plan on tackling this issue
I would test the contract state before and after the contract implementation ETA <=74hr

**Comment by jimenezz22** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am Luis Jiménez, an active member of the Dojo Coding community in Costa Rica, with experience in Cairo, having built onchain games like ByteBeasts and contributed to open-source projects such as CairoLint, where I implemented tests for Cairo lints. Additionally, I taught Cairo during the Starknet Bootcamp for Dojo Coding. I also have experience with TypeScript, contributing to Starknet Quest and Go Stark Me by developing components like ComboBoxes, among others

### How I plan on tackling this issue
Here is how I plan to approach the issue:

1. **Understand the Contract:**
    - I will thoroughly review the `FlexHausCollectible.cairo` file to understand the logic and key functions that need to be tested.
2. **Test Coverage:**
    - I will create unit test cases for each function in the contract, ensuring that all core functionality is covered.
    - Specifically, I will focus on edge cases, such as invalid inputs or boundary conditions, to ensure the contract behaves as expected in all scenarios.
3. **Implementing Tests:**
    - The tests will be implemented in the `flex_haus/tests` folder, following the structure already present in the repository. I will make sure to test against the expected outputs and handle any edge cases.
4. **Execution:**
    - I will run the tests using `scarb test` and ensure that all tests pass successfully. If any issues arise, I will communicate promptly to discuss potential solutions.

Let me know if this approach works for you, and if I can start working on this issue.

**Comment by 0xandee** [comment]
GM @blessingbytes just checking in, how're you doing?

**Comment by blessingbytes** [comment]
Hello @0xandee GM. I'm doing alright, soo sorry for the late reply, I have been working on it. I will make a pr as soon as I can
