### ISSUE TITLE
[Experimental] [MVP] implementation of YOLO Buy (continue)

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#117]
In case this is the first time you heard this, I want to implementation a cairo version of this YOLO Buy feature originally from TensorTrade. With YOLO Buy, you can place a non-refundable bid for a fraction of an NFT's listed price for a chance to win that NFT. The more you bid, the better your odds of winning. Read more: https://docs.tensor.trade/trade/yolo-buy

The contract implementation can be a separate contract(s) or best as a strategy in marketplace. And it's up to YOU to pick the way to implement enough time for ODHack! 

Draft: 
https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/pull/102
https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/issues/82#issuecomment-2324274503

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm Joseph a blockchain developer with over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
Begin by studying the codebase to ensure design consistency, then proceed to work on the task.

1. Study current codebase design
2. Leverage all provided resources within the issue to get a better grasp of the task at hand.
3. Implement the task.
4. Add tests to make sure the changes are working and no adverse effects
5. And lastly optimize

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a frontend and blockchain developer , with experiences in cairo, html,css, typescript and javascript. My background in blockchain and smart contract development would enable me to execute this solution effectively.

### How I plan on tackling this issue
To approach the problem of implementing the YOLO Buy feature in Cairo, I would first design a contract that allows users to place non-refundable bids on NFTs, with their chances of winning weighted by the size of their bids. The contract would use Cairo's efficient data structures to track bids and employ a weighted lottery to select a winner. Once the auction concludes, the contract would transfer the NFT to the winner. I would also ensure thorough testing and optimization for StarkNet, focusing on a secure, gas-efficient implementation.

**Comment by 0xandee** [comment]
GM @JoE11-y  just checking in, how're you doing?

**Comment by JoE11-y** [comment]
Yes I am.

Will send in an update by tomorrow 💪💪💪💪
