### ISSUE TITLE
[Experimental] NFT Fractionalization

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#118]
Create and work inside folder `experimental/fractional`:

**Objective:**

- Explore and implement an experimental feature that enables NFT fractionalization, allowing multiple users to own fractions of a single NFT.

**Implementation Details:**

- The design and implementation approach are at the discretion of the assignee.
- Consider various methods for fractionalization (e.g., ERC-20 token wrappers, smart contract adjustments, etc.).
- Ensure compatibility with existing NFT standards and platforms.

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Mid level Cairo developer 

### How I plan on tackling this issue
I will implement a smart contract that mints ERC-20-like tokens which will represent fractional ownership of the NFT, then i will ensure compatibility with the ERC-721 standard by integrating custom logic for ownership transfer while maintaining adherence to existing NFT standards.

**Comment by Iwueseiter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a frontend and smart contract developer.

### How I plan on tackling this issue
I will create an ERC-20 token contract that wraps around the NFT, representing fractional ownership. This would allow to lock the NFT and mint a set number of ERC-20 tokens (representing fractions of the NFT). These tokens can be distributed to users and traded on standard ERC-20 exchanges.

It would be logical to create a function to "lock" the NFT in the contract, preventing further transfers until all fractions are redeemed or ownership is consolidated.

Following the lock function, a redeem Function can be implemented to provide a way for a user to redeem their fractions for full ownership if they accumulate the required number of ERC-20 tokens.

This implementation could also ensure that the ERC-20 tokens can be traded on decentralized exchanges, allowing users to sell or buy fractions.

The ERC-721 smart contract will be modified to track ownership percentages within the contract using a mapping  to keep track of fractional owners and the percentages they own. 

Transfer Mechanism: Implement a transfer mechanism that allows fractional owners to sell or transfer a percentage of their ownership.
 
I will ensure that the contract remains compatible with existing NFT platforms (e.g., marketplaces like OpenSea) by sticking to ERC-721 standards for certain functions, while introducing custom fractional ownership logic. The fractionalized NFTs will  still comply with key ERC-721 functions like `ownerOf`, `transferFrom`, and `approve`. Metadata will not be altered by the fractionalization process, ensuring the NFT's visual and descriptive information remains accessible and accurate on platforms. I will explore how platforms like OpenSea or Rarible handle fractionalized NFTs which may guide compatibility.

**Comment by VictoriaAde** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a smart contract developer, I write Cairo and Solidity.
I will leverage my experience working with NFTs, ERC 20 and understanding of existing protocols. I'm also a member of HER D.A.O

### How I plan on tackling this issue
I will write a smart contract that locks NFTs and mints ERC-20 tokens for fractional ownership. The NFT will be securely locked while generating fractions that can be traded. I will also ensure my solution complies with existing NFT standards.

My design implementation: I will write a contract that locks the original NFT, making it non-transferable while issuing ERC-20 tokens representing fractions. 
Additionally, I will implement a mechanism for fractional owners to govern decisions regarding the NFT, such as selling it or combining shares. 
I will also allow a user to accumulate enough shares to redeem the original NFT or implement a buyout option where one owner can purchase all fractions.

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement.

### How I plan on tackling this issue
I'll be implementing this using the ERC-20 token wrappers approach, I came across an implementation using ERC-20 token wrappers so I'll be using that as an inspiration to solve this issue.

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hello, can I be assigned to work on this issue?

I'm a software developer with over 4 years experience

Here's my OnlyDust profile https://app.onlydust.com/u/raizo07

ETA: One day

**Comment by 0xandee** [comment]
GM @VictoriaAde just checking in, how're you doing?

**Comment by VictoriaAde** [comment]
Hello @0xandee, I'm doing great :)
I will make a draft PR today.

**Comment by raizo07** [comment]
Hey @0xandee can I be assigned to work on this?

**Comment by casweeney** [comment]
> Hey we're re-open this issue :)

Hi @0xandee I saw your comment that this issue is re-opened, can I handle it. I know how Fractional NFTs work and I have implemented using Solidity.

I can do same using Cairo. I have written and tested complex smart contract with Cairo. My repo has great proof of work.

## ETA: 8 - 10hours
