### ISSUE TITLE
Implement Functions' Body for Marketplace contract

### ISSUE THREAD

**Issue by ametel01** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#12]
Implement the functions' body for the [Marketplace](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/flex_marketplace/src/marketplace/market_place.cairo) contract. For reference and consistency, the implementation should align with the existing Cairo0 [`Marketplace.cairo`](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/contracts/marketplace/Marketplace.cairo) contract.

Dependencies:

scarb v2.4.0
snforge 0.13.0

Requirements:

Ensure that the code passes both `scarb fmt` and `scarb build` commands without errors, ensuring proper formatting and successful build.

**Comment by ametel01** [comment]
Happy to take this

**Comment by and1vo** [comment]
> Happy to take this

Assigning to you @ametel01 !
