### ISSUE TITLE
Fix README (without using chatgpt)

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#140]
Improve and clean up the README file, without using chatgpt. Simple as that!

**Comment by Ibinola** [comment]
Can I take this issue?

**Comment by raizo07** [comment]
May I take this issue on? I'm a Software developer with over 3 years experience and I've worked on similar issues like this one.

**Comment by abdegenius** [comment]
Could I take on this issue?

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a frontend developer with experience in creating clear and concise documentation for projects. ’ve contributed to projects by improving project documentation and ensuring it's easy to follow for both new and experienced contributors.

I would love to help improve and clean up the README file to make it more user-friendly and straightforward. I will ensure that all sections are clear, up-to-date, and organized. Please assign me this task—I’m excited to contribute to the project!

**Comment by Supa-mega** [comment]
I'd like to take this issue.

**Comment by ONEONUORA** [comment]
May I handle this? I am full stack and blockchain developer. ETA 24 hours

**Comment by deeseeker** [comment]
Could I take on this issue?

Hello, I am Qudus Adeyemi (@deeseeker), a frontend developer with over two years of experience in React, TypeScript, and JavaScript. I am currently working on a social media app for African creators (https://app.myrevva.com/).

I have worked on a similar task for Starknet React and confident I can do the same without chatgppt here too
I would love the opportunity to take on this issue.

**Comment by Mystic-Nayy** [comment]
Would love to tackle this!
I am a technical writer, i will do this effortlessly
here are some of the docs i have writen, 
https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/rkFBcGgAC,
https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/pull/92/commits/fc28412ba108a61919b75ed1d7ab2e140ce9fbd0,
https://github.com/dragan2234/worldcoin-scroll-bridge/pull/29,

**Comment by GideonBature** [comment]
Is this issue still available?

My name is Gideon Bature, a Software Engineer. I have written documentations of projects, have improved existing ones also. If given the opportunity, will send my first PR in 72 hours.

Thank you!

**Comment by emarc99** [comment]
I have done similar work in an OD project. I did this for my team project https://github.com/emarc99/anima_lib_team98/blob/develop/README.md

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3Bridge. I have contributed before to other projects like:
• CoinSafe
• Scaffold-ETH
• BuidlGuidl

I am a frontend developer, proficient in ReactJS/NextJS, TypeScript, Solidity, and Cairo.

Can I work on this issue?

Plan to Solve the Issue:

Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by chigozzdevv** [comment]
Hello boss :)
I'd love to work on this!

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. 
If assigned this i would complete it within 2 days. 

Here are some articles i have written: https://medium.com/@emma.onyedika.okeke

**Comment by kayceeDev** [comment]
Can I tackle this one?

**Comment by aurlic** [comment]
Hey I would love to be assigned to this issue and help the project going forward.

**Comment by Thibrac** [comment]
I want to continue to develop the projects, it's a small contribution but step by step we progress ;)

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by pheobeayo** [comment]
Can I take this from here?
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest, Bandada and Speedrun scaffold-stark
My Approach includes:
- Reviewing of existing Documentation:
by thoroughly reading the current documentation, including README files, code comments, and any other relevant documentation provided in the repository.
Identify areas that are unclear, outdated, or missing crucial information that would be of benefit to users and developers.
- Make note of changes and define all code snippets and technical terms in simple terms.
- Create a Pull Request (PR).
- Request for a Review.
- Make changes based on the review of the PR.

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer with expertise in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.
I will improve and clean up the README file to make it more clear, structured, and easy to understand. I will ensure that all relevant information is included and presented in a user-friendly way.
Please assign this issue to me.

Thank you!

**Comment by jaykayudo** [comment]
Can i work on this?

I will make sure not to use LLMs

**Comment by Amarjeet325** [comment]
Can I take this issue?

**Comment by Benjtalkshow** [comment]
May I try my hand at this?

**Comment by Michaelkingsdev** [comment]
I’d like to help with this.

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by TheSQLguy** [comment]
i am new to open source and I’d love to work on this task.
So, I will improve and clean up the README file by removing redundant sections, ensuring a clear structure, and enhancing readability. I'll focus on making the instructions more concise and ensure all necessary information is easy to follow. This will improve the overall clarity and organization of the README.

**Comment by emmz3230** [comment]
I’d love to work on this task.
My approach to cleaning up the README is to talk about the project's way of installation and the version of Cairo needed and what is needed in the PC to install the project, the version used to build the project, how to run the project, and contribution if needed.

**Comment by SimplementeCao** [comment]
I would love to work on this topic, I have already solved documentation issues and I would have no problem solving this one as well.

**Comment by savagechucks** [comment]
I'm Isaac, a new contributor. I'm a frontend dev and this is my first time trying out an issue.
I'd appreciate if I can be assigned this issue.
ETA: 2days

**Comment by DuendexCR** [comment]
Could I take a shot at this?

**Comment by Iwueseiter** [comment]
Mind if I take this issue?
I'm a technical writer, frontend and smart contract developer. I will go through all that i need to implement in this task and get it done without using chatgpt . 
ETA: 24hrs

**Comment by Nityam573** [comment]
Can I handle this task?

**Comment by Psalmuel01** [comment]
Can I work on this, please?
Excellent command of English, no chatgpt.
ETA: 8 hours
Lovely project, btw.

**Comment by Yunusabdul38** [comment]
Can I jump on this task?

**Comment by SudiptaPaul-31** [comment]
I'd like to handle this task.

**Comment by 3th-Enjay** [comment]
May I handle this issue?

**Comment by Kingsuite** [comment]
May I take care of this?

**Comment by binayak9932** [comment]
@0xandee can I work  on this issue?

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust.
If assigned this i would complete it within 2 days.

Here are some articles i have written: https://medium.com/@emma.onyedika.okeke
