### ISSUE TITLE
[Experimental] ERC-4907 Rental NFT

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#141]
Create and work inside folder `experimental/erc_4907_rental_nft`:

It proposes an additional interface for NFTs to be used as recurring, expirable subscriptions. The interface includes functions to renew and cancel the subscription.

**Implementation Details:**
- The design and approach are left to the discretion of the assignee.
- Some NFTs have certain utilities. For example, virtual land can be “used” to build scenes, and NFTs representing game assets can be “used” in-game. In some cases, the owner and user may not always be the same. There may be an owner of the NFT that rents it out to a “user”. The actions that a “user” should be able to take with an NFT would be different from the “owner” (for instance, “users” usually shouldn’t be able to sell ownership of the NFT).  In these situations, it makes sense to have separate roles that identify whether an address represents an “owner” or a “user” and manage permissions to perform actions accordingly.

**Reference:** https://eips.ethereum.org/EIPS/eip-4907

**Comment by SoarinSkySagar** [comment]
May I work on this one @0xandee ?

approach: i will check out the specs of the erc from the provided link and make sure to implement it. 

eta: 5 days

**Comment by blessingbytes** [comment]
pls i would love to work on this issue

**Comment by manlikeHB** [comment]
Hi, I am a returning contributor on this project, I would like to work on this.

**Comment by Supa-mega** [comment]
Can I start working on this?

**Comment by casweeney** [comment]
## I have great experience with NFTs
- I will study the reference link provided and I will create an ERC-4907 as specified in the description.

## ETA - 10hours

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ShantelPeters** [comment]
May I be assigned to this?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer with expertise in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.

I will implement ERC-4907 to enable NFTs as recurring, expirable subscriptions, allowing separate roles for "owner" and "user." I will design functions for subscription renewal and cancellation while managing user and owner permissions.

Please assign this issue to me.

Thank you!

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by suhas-sensei** [comment]
Having experience with similar NFT standards like ERC-721 and role-based systems, I'll ensure proper implementation of the rental and subscription mechanics following the EIP-5643 pattern. I will focus on creating dual roles for owners/renters, subscription-based rental periods, and access control functions as requested.

**Comment by TheSQLguy** [comment]
Here, I will make the folder experimental/erc_4907_rental_nft and implement the proposed NFT functionality as a repeating, expiring subscription. This standard introduces the idea of "owner" and "user" roles, enabling users to rent NFTs for a defined time period with renewal or subscription cancellation capabilities. I also manage permissions such that interaction with the NFT would not transfer ownership, per the guidelines laid out in the referenced EIP.

**Comment by caxtonacollins** [comment]
Is this issue still available?

**Comment by DuendexCR** [comment]
Could I take over this issue?

**Comment by RajeshRk18** [comment]
Hi! I am Rajesh. I am a solidity developer. I have experience implementing NFT contracts, access control, voting contracts, vesting wallet contracts, and proxy (erc 1967) contracts. So, I can take up this issue. I will make sure the contract works as expected through testing.

Here is the initial interface I defined for this contract:

```solidity
interface ISubscriptionNFT {
    // User Management (ERC-4907)
    function setUser(uint256 tokenId, address user, uint64 expires) external;
    function userOf(uint256 tokenId) external view returns (address);
    function userExpires(uint256 tokenId) external view returns (uint256);

    // Subscription Management (ERC-5643)
    function renewSubscription(uint256 tokenId, uint64 duration) external payable;
    function cancelSubscription(uint256 tokenId) external payable;
    function expiresAt(uint256 tokenId) external view returns (uint64);
    function isRenewable(uint256 tokenId) external view returns (bool);

    // Additional Functions
    function mint(address recipient, uint64 initialDuration) external payable;
    function setSubscriptionPrice(uint256 newPrice) external;
    function withdrawFunds() external;

    // Events
    event UpdateUser(uint256 indexed tokenId, address indexed user, uint64 expires);
    event SubscriptionUpdate(uint256 indexed tokenId, uint64 expiration);
    event SubscriptionPriceChanged(uint256 newPrice);
}
```

ETA: 3 days

**Comment by SudiptaPaul-31** [comment]
Can i work on this

I am a blockchain developer and had worked on many starknet projects in previous odhack and a beginner in cairo but would love to work on this issue

My approach: will checkout the specifications from the erc and will try to implement it

ETA-5days

**Comment by RajeshRk18** [comment]
@0xandee The issue title is about [ERC-4907](https://eips.ethereum.org/EIPS/eip-4907). But the description is for [ERC-5643](https://eips.ethereum.org/EIPS/eip-5643) which was already implemented [here](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/tree/main/experimental/erc_5643_subscription_nft). 
Can you please update?
