### ISSUE TITLE
[Experimental] ERC-7662 AI Agent NFTs

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#143]
Create and work inside folder `experimental/erc_7662_ai_agent_nft`:

This proposal introduces a standard for AI agent NFTs. In order for AI Agents to be created and traded as NFTs it doesn’t make sense to put the prompts in the token metadata, therefore it requires a standard custom struct. It also needs doesn’t make sense to store the prompts directly onchain as they can be quite large, therefore this standard proposes they be stored as decentralized storage URLs. This standard also proposes two options on how this data should be made private to the owner of the NFT, with the favored implementation option being encrypting the data using custom contract parameters for decryption that decrypt only to the owner of the NFT.

**Implementation Details:**
- The design and approach are left to the discretion of the assignee.
- The creation and trading of AI Agent NFTs are a natural fit and offer the potential for an entirely new onchain market. This requires some custom data to be embedded in the NFT through a custom struct and this needs to be standardized so that any marketplace or AI Agent management product, among others, know how to create and parse AI Agent NFTs.

**Reference:** https://eips.ethereum.org/EIPS/eip-7662

**Comment by beeguy74** [comment]
Hi, I am a beginner Cairo developer from Paris.
Closed 2 tasks on cairo on 10 ODHACK.
I am very interested in AI models and it will be a great challenge for me to implement this contract for you.
I don't promise to finish the issue quickly because your project is new to me =)
But I intend to do a decent job and at least do the draft PR within 48 hours.
Could I try solving this?

**Comment by beeguy74** [comment]
Hi, I am a beginner Cairo developer from Paris.
Closed 2 tasks on cairo on 10 ODHACK.
I am very interested in AI models and it will be a great challenge for me to implement this contract for you.
I don't promise to finish the issue quickly because your project is new to me =)
But I intend to do a decent job and at least do the draft PR within 48 hours.
Could I try solving this?

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by trashcancries** [comment]
May I work on this one @0xandee ?

approach: i will check out the specs of the erc from the provided link and make sure to implement it.

eta: 5 days

**Comment by ShantelPeters** [comment]
I'd like to handle this task.

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer with expertise in Cairo, Rust, Solidity, Aptos, and web development.

I will implement the ERC-7662 AI Agent NFTs standard as per the proposal, including custom struct handling for AI prompts stored as decentralized URLs and ensuring that the data is encrypted for owner-only access.

Please assign this issue to me.

Thank you!

**Comment by TheSQLguy** [comment]
So I will create the experimental/erc_7662_ai_agent_nft folder and implement the AI agent NFT standard, described in EIP-7662. This means setting up a custom struct for the metadata of an NFT, storing the prompts in decentralized storage, and ensuring the privacy of the owner by using encryption techniques. The design will then guarantee compatibility with AI Agent management platforms and marketplaces.

**Comment by suhas-sensei** [comment]
having the required experience in this regard, I'll ensure the prompt data remains private while maintaining efficient marketplace integration for these AI agent tokens.
ill try developing a system for encrypted prompt storage using decentralized URLs, with struct-based metadata handling and owner-specific decryption mechanisms. Having experience with NFT standards and cryptographic implementations,

**Comment by caxtonacollins** [comment]
Can I tackle this one?

**Comment by DuendexCR** [comment]
Could I take over this issue?

**Comment by tosinmoses384** [comment]
Would love to tackle this!

**Comment by blessingbytes** [comment]
pls, i would love to work on this

**Comment by binayak9932** [comment]
May I work on this one @0xandee ?  i am a regular contributor  starknet ecosystem repos. I will check out the specs of the erc from the provided link and  implement it.

**Comment by SudiptaPaul-31** [comment]
Can i work on this

I am a blockchain developer and had worked on many starknet projects in previous odhack and a beginner in cairo but would love to work on this issue

My approach: will checkout the specifications from the erc and will try to implement it

ETA-5days
