### ISSUE TITLE
[Experimental] ERC-5585 NFT Authorization

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#144]
Create and work inside folder `experimental/erc_5585__nft_authorization`:

This EIP separates the [ERC-721](https://eips.ethereum.org/EIPS/eip-721) NFT’s commercial usage rights from its ownership to allow for the independent management of those rights.

**Implementation Details:**
- The design and approach are left to the discretion of the assignee.
- Most NFTs have a simplified ownership verification mechanism, with a sole owner of an NFT. Under this model, other rights, such as display, or creating derivative works or distribution, are not possible to grant, limiting the value and commercialization of NFTs. Therefore, the separation of an NFT’s ownership and user rights can enhance its commercial value.
- Commercial right is a broad concept based on the copyright, including the rights of copy, display, distribution, renting, commercial use, modify, reproduce and sublicense etc. With the development of the Metaverse, NFTs are becoming more diverse, with new use cases such as digital collections, virtual real estate, music, art, social media, and digital asset of all kinds. The copyright and authorization based on NFTs are becoming a potential business form.

**Reference:** https://eips.ethereum.org/EIPS/eip-5585

**Comment by SoarinSkySagar** [comment]
May I work on this one @0xandee ?

approach: i will check out the specs of the erc from the provided link and make sure to implement it. 

eta: 5 days

**Comment by beeguy74** [comment]
Hi, I am a beginner Cairo developer from Paris. 
Closed 2 tasks on cairo on 10 ODHACK. 
I don't promise to finish the issue quickly because your project is new to me =)
But I intend to do a decent job and at least do the draft PR within 48 hours.
Could I try solving this?

**Comment by blessingbytes** [comment]
Can I take care of this issue?

**Comment by OkoliEvans** [comment]
This issue looks great and interesting. Can I take this ?

 I have extensive experience building Cairo contracts for a year plus now, and have already contributed to numerous projects on Starknet including ArtPeace, Cairo book, Custos Diretriez and so on, and I will really love to research and work on this. @0xandee

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by trashcancries** [comment]
May I work on this one @0xandee ?

approach: i will check out the specs of the erc from the provided link and make sure to implement it.

eta: 5 days

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Kachimercy1** [comment]
I'd love to give this a go.

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer with expertise in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.

I will implement EIP-5585 by separating ERC-721 NFT’s ownership from commercial rights, enabling independent management of usage rights, such as copy, display, and distribution, to enhance NFT commercialization.

Please assign this issue to me.

Thank you!

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by TheSQLguy** [comment]
I am new to open source.
I will make a folder called experimental/erc_5585_nft_authorization, implement separation of commercial usage rights from NFT ownership according to EIP-5585, and therefore independently manage the rights to display, to create derivative works, and for commercial use in the value of the NFT. Design and approach will be flexible and at the same time in conformity with the proposed standard.

**Comment by suhas-sensei** [comment]
Having worked with access control systems and NFT standards, I'll ensure proper management of these distinct rights while maintaining ERC-721 compatibility. If assigned, i will try  creating a system that separates ownership rights from usage rights, with granular permission controls for different commercial activities (display, distribution, derivatives, etc.)

**Comment by DuendexCR** [comment]
I’m interested in this one.

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, Cairo and Rust.

To solve this issue, I’ll take the following steps:
I will extend and build upon the ERC-721 standard to enable separate management of ownership and commercial rights. Ownership will be tracked using a mapping(uint256 => address owner) while rights will be stored in a nested mapping: mapping(uint256 => mapping(address => Rights[])).

I will define a Rights enum to specify various commercial rights.

Implement Rights Management Functions:
assignRights(uint256 tokenId, address user, Rights[] memory rights) to assign rights to a user.
revokeRights(uint256 tokenId, address user) to revoke a user’s rights.
hasRight(uint256 tokenId, address user, Rights right) to check if a user has a specific right.
transferRights(uint256 tokenId, address from, address to) to transfer rights to another user.
Maintain Independence: Ownership will be handled by the ERC-721 standard, while rights management will operate independently using a separate mapping.

Emit Events:
RightsAssigned(uint256 tokenId, address user, Rights[] rights) upon rights assignment.
RightsRevoked(uint256 tokenId, address user) upon rights revocation.
RightsTransferred(uint256 tokenId, address from, address to) upon rights transfer.
Write Unit Tests: I will test rights assignment, revocation, transfer, and retrieval to ensure functionality and ERC-721 compliance for ownership handling.

Will love to take care of this issue, please assign me.

**Comment by binayak9932** [comment]
May I work on this one @0xandee ?  i am a regular contributor  starknet ecosystem repos. I will check out the specs of the erc from the provided link and  implement it.

**Comment by SudiptaPaul-31** [comment]
Can i take this issue

I am a blockchain developer and had worked on many starknet projects in previous odhack and a beginner in cairo but would love to work on this issue

My approach to resolve this : will checkout the specifications from the erc and will try to implement it

ETA-5days

**Comment by ekumamatthew** [comment]
May I try my hand at this?

**Comment by suhas-sensei** [comment]
thanks for the opportunity.
