### ISSUE TITLE
[Experimental] ERC-5006 Rental NFT

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#145]
Create and work inside folder `experimental/erc_5006_rental_nft`:

This standard is an extension of [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155). It proposes an additional role (user) which can be granted to addresses that represent a user of the assets rather than an owner.

**Implementation Details:**
- The design and approach are left to the discretion of the assignee.
- Like [ERC-721](https://eips.ethereum.org/EIPS/eip-721), [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155) tokens may have utility of some kind. The people who “use” the token may be different than the people who own it (such as in a rental). Thus, it would be useful to have separate roles for the “owner” and the “user” so that the “user” would not be able to take actions that the owner could (for example, transferring ownership).

**Reference:** [_](https://eips.ethereum.org/EIPS/eip-5006)

**Comment by raizo07** [comment]
Is it okay if I tackle this? I'm a Software developer with over 3 years experience

**Comment by JoE11-y** [comment]
Can I attempt this issue?

**Comment by manlikeHB** [comment]
Hi, I am a returning contributor and a Cairo Developer with great experience contributing to lots of amazing Cairo projects. Could I be assigned to this?

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a smart contract developer with expertise in NFTs and blockchain technologies. I have worked extensively with ERC-721 and ERC-1155 tokens and have a strong understanding of how token standards can be extended to introduce new functionalities, such as multi-role support.

I would love to contribute to the development of this ERC-1155 extension by introducing the "user" role to distinguish between token owners and users. With my experience in smart contract development and role-based access control, I am confident I can implement this extension effectively to allow for distinct roles in token usage. Please assign me this task—I look forward to contributing to the project!

**Comment by caxtonacollins** [comment]
I will love to start working on this. Please assign me. ETA 48hrs

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by trashcancries** [comment]
May I work on this one @0xandee ?

approach: i will check out the specs of the erc from the provided link and make sure to implement it.

eta: 5 days

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer with expertise in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.
I will implement ERC-5006 by extending ERC-1155 to separate roles for “owner” and “user,” allowing rental functionality where users can access assets without being able to transfer ownership.

Please assign this issue to me.

Thank you!

**Comment by TheSQLguy** [comment]
I am new to open source
So I will implement ERC-5006 inside the experimental/erc_5006_rental_nft folder, extending ERC-1155 to add a new "user" role separate from the "owner." This will allow users to interact with the assets without the ability to transfer ownership, supporting use cases like rental systems. The design and approach will be flexible, following the provided requirements.

**Comment by suhas-sensei** [comment]
Can I contribute to this one? I'll implement the ERC-1155 rental extension in experimental/erc_5006_rental_nft, developing a system that introduces a distinct 'user' role separate from ownership, with time-bound rental functionality and proper access controls.
I'll ensure clear separation between owner and user permissions while maintaining the token standard's compatibility.

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to solve this issue please. I am good with tests and I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo

To solve this issue, I'll take the following steps:
1. I'll create a directory experimental/erc_5006_rental_nft with subfolders like contracts/, test/, and scripts/ for modular organization of source code, tests, and deployment scripts. I'll extend ERC-1155 using OpenZeppelin's library and add a UserInfo struct to store the user address and expiresAt timestamp.
I'll implement functions such as, assignUser(uint256 tokenId, address user, uint64 duration) to assign a "user" role to a token for a specified duration, callable only by the token owner, userInfo(uint256 tokenId) to fetch the current "user" and expiration details for a token and isUser(uint256 tokenId, address user) to verify if a user has active rights to a token based on ownership and expiration.
2. I'll ensure only token owners can call assignUser to prevent unauthorized user assignment and restrict sensitive actions such as transferring tokens, to owners.
3. Lastly, I'll write unit tests using Hardhat or Foundry to validate assignUser assigns the role correctly, test the expiration of the "user" role using time manipulation and also verify unauthorized actions are blocked for non-owners.

Kindly assign me please, I'm up for the task

**Comment by DuendexCR** [comment]
Can I contribute to this one?

**Comment by blessingbytes** [comment]
pls, may i handle this issue

**Comment by Dorcas18** [comment]
Could I grab this task?

**Comment by binayak9932** [comment]
May I work on this one @0xandee ?  i am a regular contributor  starknet ecosystem repos. I will check out the specs of the erc from the provided link and  implement it.
