### ISSUE TITLE
[Experimental] ERC-6105 No Intermediary NFT Trading Protocol

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#149]
Create and work inside folder `experimental/erc_6105_no_intermediary_nft_trading_protocol`:

This ERC adds a marketplace functionality to [ERC-721](https://eips.ethereum.org/EIPS/eip-721) to enable non-fungible token trading without relying on an intermediary trading platform. At the same time, creators may implement more diverse royalty schemes.

**Implementation Details:**
- The design and approach are left to the discretion of the assignee.
- Most current NFT trading relies on an NFT trading platform acting as an intermediary, which has lots of problems.

**Reference:** https://eips.ethereum.org/EIPS/eip-6105

+ TODO later:  Optional item offer extension and Optional collection offer extension

**Comment by SoarinSkySagar** [comment]
May I work on this one @0xandee ?

approach: i will check out the specs of the erc from the provided link and make sure to implement it. 

eta: 5 days

**Comment by blessingbytes** [comment]
i would love to work on this task

**Comment by manlikeHB** [comment]
Hi, I am a Cairo Developer with great experience contributing to lots of amazing Cairo projects. can I work on this?

**Comment by Supa-mega** [comment]
I'd be happy to do this.

**Comment by caxtonacollins** [comment]
I will love to start working on this. Please assign me.

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by trashcancries** [comment]
May I work on this one @0xandee ?

approach: i will check out the specs of the erc from the provided link and make sure to implement it.

eta: 5 days

**Comment by ShantelPeters** [comment]
Can I contribute to this one?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer with expertise in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.

I will implement the ERC-6105 No Intermediary NFT Trading Protocol to enable peer-to-peer trading of NFTs, removing the need for intermediary platforms. This will also allow creators to implement more diverse royalty schemes as described in the standard.

Please assign this issue to me.

Thank you!

**Comment by TheSQLguy** [comment]
To address this issue, I would:

Create a folder,  mkdir experimental/erc_6105_no_intermediary_nft_trading_protocol in the repository.
Design and implement a smart contract based on ERC-6105, incorporating built-in marketplace functionality with ERC-721, while supporting custom royalty schemes.
Document the structure and functioning of the contract in a README.md to be created inside the folder.
Thorough testing of the contract for compliance with ERC-6105 and edge cases in trading and royalty distribution.

**Comment by suhas-sensei** [comment]
Can I attempt this issue? Having implemented marketplace contracts and token standards before, I'll ensure secure trading mechanisms while maintaining flexible royalty distribution systems. 
"I'll implement the no-intermediary NFT trading protocol and test out changes necessary, if assigned. Looking forward.

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to solve this issue please. I am good with tests and I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo

To solve this issue, I'll take the following steps:
1. I'll define IERC6105 with methods setSaleDetails, purchase, and setRoyaltyScheme for listing, purchasing, and royalty management. I'll use mappings for sales details and RoyaltyInfo structures to store recipients and percentages. I'll implement direct purchase via purchase with msg.value validation and ownership transfer and also calculate and distribute royalty splits during transactions using price * percentage / 100.
2. I'll ensure royalty percentages sum to ≤100% and verify msg.value against the listing price. I'll use nonReentrant modifiers for critical functions and emit SaleCreated, NFTPurchased, and RoyaltySet for transparency and tracking.
3. Lastly, I'll test.

Kindly assign me please, I'm up for the task

**Comment by DuendexCR** [comment]
May I try my hand at this?

**Comment by RajeshRk18** [comment]
### About me

Hi! I am Rajesh. I have experience in Rust, Cairo, Noir, and Python. I have experience implementing NFT contracts, access control, voting contracts, vesting wallet contracts, and proxy (erc 1967) contracts. Also, I have contributed to some Cairo projects! So, I can take up this issue.

### How I will solve this issue?

- Implement the IERC6105 interface, defining storage for listings, including salePrice, expires, supportedToken, and benchmarkPrice.
- Develop listItem and delistItem functions to enable NFT owners o to list and remove tokens for sale, emitting the UpdateListing event.
- Implement buyItem to handle token purchases, ensuring proper validation (price, payment token, and royalties), ownership transfer, and emitting the Purchased event.
- Incorporate royalty calculations using benchmarkPrice and handle secure payment transfers to sellers and royalty recipients.
- Provide a getListing function to query listing details and implement validation checks for ownership, expiration, and listing conditions to prevent misuse.
- Use require statements to prevent invalid listings and front-running attacks. Ensure atomicity in the buyItem function to avoid payment mismatches or incomplete transfers.
- Write tests for all functions, covering edge cases like expired listings and invalid tokens.

ETA: 3days

**Comment by savagechucks** [comment]
Hello, I'm a new contributor.
I go by the name Isaac. 
I would like to take the chance to tackle this issue.
ETA: 2days

**Comment by Dorcas18** [comment]
I'd love to give this a go.

**Comment by binayak9932** [comment]
May I work on this one @0xandee ?  i am a regular contributor  starknet ecosystem repos. I will check out the specs of the erc from the provided link and  implement it.

**Comment by ekumamatthew** [comment]
I'd like to take this issue.
