### ISSUE TITLE
Implement Functions' Body for TransferSelectorNFT contract

### ISSUE THREAD

**Issue by ametel01** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#15]
Implement the functions' body for the [TransferSelectorNFT](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/flex_marketplace/src/marketplace/transfer_selector_NFT.cairo) contract. For reference and consistency, the implementation should align with the existing Cairo0 [`TransferSelectorNFT.cairo`](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/contracts/marketplace/TransferSelectorNFT.cairo) contract.

Dependencies:
scarb v2.4.0
snforge 0.13.0

Requirements:

Ensure that the code passes both `scarb fmt` and `scarb build` commands without errors, ensuring proper formatting and successful build.

**Comment by VictorONN** [comment]
Can I take this?

**Comment by and1vo** [comment]
> Can I take this?

Assigning to you @VictorONN !

**Comment by 0xandee** [comment]
Yo any updates on this sir @VictorONN

**Comment by and1vo** [comment]
I'll keep this open yeah

**Comment by and1vo** [comment]
Since @ametel01 is making PR to close this, I'm gonna assign to him yeah @VictorONN . I'll create more upcomming issues for you to contribute, don't worry Vic, Cheers!
