### ISSUE TITLE
Complete all the test cases for ExecutionManager

### ISSUE THREAD

**Issue by ametel01** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#32]
Complete the test cases in [test](https://github.com/ametel01/Flex-Marketplace-Contract/blob/main/flex_marketplace/tests/execution_manager_test.cairo).

All contract are deployed and dispatcher initialized, refer to [test utils](https://github.com/ametel01/Flex-Marketplace-Contract/blob/main/flex_marketplace/tests/utils.cairo) for details.

use `scarb run test` to run all the tests, or `scarb run test <test_name>` to run a specific test. 
Adjust the `#[should_panic()]` decorator error message based on the test case, refer to starknet foundry [docs](https://foundry-rs.github.io/starknet-foundry/testing/testing.html?highlight=exp#expected-failures) for detailed implementation.

All test cases are required to `PASS`

**Comment by Realkayzee** [comment]
can i take this up?

**Comment by 0xandee** [comment]
> can i take this up?

Sure! Assigning to you!

**Comment by AniDhumal** [comment]
Hi @0xandee, can i take this?

**Comment by 0xandee** [comment]
> @0xandee can i take this?
> 
> 

I think @Realkayzee is currently assigned

**Comment by Realkayzee** [comment]
I have already submitted a pull request, tested it, but hasn't been merged yet.

**Comment by 0xandee** [comment]
> I have already submitted a pull request, tested it, but hasn't been merged yet.

![image](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/assets/34095856/867cb421-7838-44fd-91a7-d4ca8b2c384d)

Nice! But I think it's failed to pass build and test check, do you mind take a look?

**Comment by Realkayzee** [comment]
> > I have already submitted a pull request, tested it, but hasn't been merged yet.
> 
> ![image](https://private-user-images.githubusercontent.com/34095856/298298725-867cb421-7838-44fd-91a7-d4ca8b2c384d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NzMxMjQsIm5iZiI6MTcwNTc3MjgyNCwicGF0aCI6Ii8zNDA5NTg1Ni8yOTgyOTg3MjUtODY3Y2I0MjEtNzgzOC00NGZkLTkxYTctZDRjYThiMmMzODRkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxNzQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjQzNGZjMTU1MTExMGYxYjQ1NTYwZmRhMDdkNWM0NGE0Yjg1MmFlMGQ4NTJmMmFiZmZiMTA3ZmU0NzY1OWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3iTpzmW4GUgr6FMwf9guOil0ixKKys_Ydmjq2Nz-ezg)
> 
> Nice! But I think it's failed to pass build and test check, do you mind take a look?

Okay,

**Comment by AniDhumal** [comment]
> @0xandee @AniDhumal I have already submitted a pull request, tested it, but hasn't been merged yet.

ahh cool no worries
