### ISSUE TITLE
Complete all tests for RoyaltyFeeManager

### ISSUE THREAD

**Issue by ametel01** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#36]
Complete the test cases in [test](https://github.com/ametel01/Flex-Marketplace-Contract/blob/main/flex_marketplace/tests/royalty_fee_managen_test.cairo).

All contract are deployed and dispatcher initialized, refer to [test utils](https://github.com/ametel01/Flex-Marketplace-Contract/blob/main/flex_marketplace/tests/utils.cairo) for details.

use `scarb run test` to run all the tests, or `scarb run test <test_name>` to run a specific test. 
Adjust the `#[should_panic()]` decorator error message based on the test case, refer to starknet foundry [docs](https://foundry-rs.github.io/starknet-foundry/testing/testing.html?highlight=exp#expected-failures) for detailed implementation.

All test cases are required to `PASS`

**Comment by VictorONN** [comment]
Hello, I wanna work on this please

**Comment by 0xandee** [comment]
> Hello, I wanna work on this please

You can pick any test issue!

**Comment by VictorONN** [comment]
Ok, am almost there.

**Comment by VictorONN** [comment]
Let me push, you'll tell me where am going wrong. Am using the references as best as I could
