### ISSUE TITLE
Implement Functions' Body for Proxy Contract

### ISSUE THREAD

**Issue by ametel01** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#4]
Implement the functions' body for the [Proxy](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/flex_marketplace/src/marketplace/proxy.cairo) contract. For reference and consistency, the implementation should align with the existing Cairo0 [`Proxy.cairo`](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/contracts/marketplace/Proxy.cairo) contract.

Dependencies:

scarb v2.4.0
snforge 0.13.0

Requirements:

Ensure that the code passes both `scarb fmt` and `scarb build` commands without errors, ensuring proper formatting and successful build.

**Comment by ametel01** [comment]
happy to take this

**Comment by ametel01** [comment]
@and1vo having had a better look to this i don't think we need a proxy at all, we can just implement upgradable component in contracts that need upgrading.

**Comment by and1vo** [comment]
> @and1vo having had a better look to this i don't think we need a proxy at all, we can just implement upgradable component in contracts that need upgrading.

Great! I think we can close this, thanks for the heads up!
