### ISSUE TITLE
Implement Functions' Body for CurrencyManager Contract

### ISSUE THREAD

**Issue by ametel01** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#5]
Implement the functions' body for the [CurrencyManager](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/flex_marketplace/src/marketplace/currency_manager.cairo) contract. For reference and consistency, the implementation should align with the existing Cairo0 [`CurrencyManager.cairo`](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/contracts/marketplace/CurrencyManager.cairo) contract.

Dependencies:

scarb v2.4.0
snforge 0.13.0

Requirements:

Ensure that the code passes both `scarb fmt` and `scarb build` commands without errors, ensuring proper formatting and successful build.

**Comment by Mohiiit** [comment]
I can take this up.

**Comment by ametel01** [comment]
Wait for the repo owner to assign issues. Also since it looks like a community driven project a good practice would be to only apply to only one issue at a time to allow others to join.

**Comment by and1vo** [comment]
> I can take this up.

Assigning this to you ! @Mohiiit 

> Wait for the repo owner to assign issues. Also since it looks like a community driven project a good practice would be to only apply to only one issue at a time to allow others to join.

Agree!

**Comment by 0xandee** [comment]
hey @ametel01 this issue is available for you to grab! Happy to assign to ya!
