### ISSUE TITLE
Complete integration tests for Creating Listing and Buy actions

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#51]
Complete the test cases in test.

All contract are deployed and dispatcher initialized, refer to test utils for details.

use scarb run test to run all the tests, or scarb run test <test_name> to run a specific test.
Adjust the #[should_panic()] decorator error message based on the test case, refer to starknet foundry docs for detailed implementation.

All test cases are required to PASS

**Comment by TAdev0** [comment]
Hey @0xandee , is this issue still available?

**Comment by 0xandee** [comment]
> Hey @0xandee , is this issue still available?

Yeah you can take it if you want!

**Comment by TAdev0** [comment]
Let's do this @0xandee  !

**Comment by TAdev0** [comment]
@0xandee  I just checked quickly the codebase and the tests folder, may i get a bit more of guidance about what needs to be tested exactly?

**Comment by 0xandee** [comment]
> @0xandee I just checked quickly the codebase and the tests folder, may i get a bit more of guidance about what needs to be tested exactly?

I'll write a quick diagram flow for everyone to catchup
