### ISSUE TITLE
Complete integration tests for Creating Offer and Accept Offer actions

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#52]
Complete the test cases in test.

All contract are deployed and dispatcher initialized, refer to test utils for details.

use scarb run test to run all the tests, or scarb run test <test_name> to run a specific test.
Adjust the #[should_panic()] decorator error message based on the test case, refer to starknet foundry docs for detailed implementation.

All test cases are required to PASS

**Comment by Realkayzee** [comment]
Can i take this up?
