### ISSUE TITLE
Complete integration tests for Cancel Listing and Cancel Offer actions

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#53]
Complete the test cases in test.

All contract are deployed and dispatcher initialized, refer to test utils for details.

use scarb run test to run all the tests, or scarb run test <test_name> to run a specific test.
Adjust the #[should_panic()] decorator error message based on the test case, refer to starknet foundry docs for detailed implementation.

All test cases are required to PASS

**Comment by Pelumi527** [comment]
Hi I would like to work on this

**Comment by Pelumi527** [comment]
Hi. Sorry I had some issues that is why I haven't been able to contribute to the project, but I am back now.
Got some question, current running `snforge test` on my end returns failure for all the test cases, it that right?
