### ISSUE TITLE
Implement Functions' Body for  StrategyStandardSaleForFixedPrice contract

### ISSUE THREAD

**Issue by ametel01** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#7]
Implement the functions' body for the [StrategyStandardSaleForFixedPrice](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/flex_marketplace/src/marketplace/strategy_standard_sale_for_fixed_price.cairo) contract. For reference and consistency, the implementation should align with the existing Cairo0 [`StrategyStandardSaleForFixedPrice.cairo`](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/contracts/marketplace/StrategyStandardSaleForFixedPrice.cairo) contract.

Dependencies:

scarb v2.4.0
snforge 0.13.0

Requirements:

Ensure that the code passes both `scarb fmt` and `scarb build` commands without errors, ensuring proper formatting and successful build.

**Comment by AniDhumal** [comment]
Can I take this up?

**Comment by and1vo** [comment]
> Can I take this up?

Assigning to ya @AniDhumal
