### ISSUE TITLE
Implement Functions' Body ExecutionManager contract

### ISSUE THREAD

**Issue by ametel01** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#8]
Implement the functions' body for the [ExecutionManager](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/flex_marketplace/src/marketplace/execution_manager.cairo) contract. For reference and consistency, the implementation should align with the existing Cairo0 [`ExecutionManager.cairo`](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/contracts/marketplace/ExecutionManager.cairo) contract.

Dependencies:

scarb v2.4.0
snforge 0.13.0

Requirements:

Ensure that the code passes both `scarb fmt` and `scarb build` commands without errors, ensuring proper formatting and successful build.

**Comment by Mohiiit** [comment]
I want to work on this.

**Comment by and1vo** [comment]
> I want to work on this.

Assigning this to you @Mohiiit ~

**Comment by Mohiiit** [comment]
#20

**Comment by and1vo** [comment]
Hey @ametel01 do you want to take this up? Happy to reassign to ya!
