### ISSUE TITLE
feat: MVP implementation of YOLO Buy

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#82]
In case this is the first time you heard this, I want to implementation a cairo version of this YOLO Buy feature originally from TensorTrade. With YOLO Buy, you can place a non-refundable bid for a fraction of an NFT's listed price for a chance to win that NFT. The more you bid, the better your odds of winning. Read more: https://docs.tensor.trade/trade/yolo-buy

The contract implementation can be a separate contract(s) or best as a strategy in marketplace. And it's up to YOU to pick the way to implement enough time for ODHack!

If you feel the implementation is take more than 1 person effort, I'll consider 2 assignees to work together for this issue!

**Comment by ooochoche** [comment]
Hi

**Comment by kateberryd** [comment]
Hi

**Comment by manlikeHB** [comment]
hi

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hi, I’m a Cairo dev and I’ve had experiences contributing to lots of open source Cairo projects, I’m confident I can implement this feature within 5 - 7 working days and I can handle this issue myself.

### How I plan on tackling this issue
This is a rough roadmap on how I will implementing the feature, I’d obviosly be making necessary changes/improvements as i implement;

- First off I will go through the repo to get a better understanding of the project.
- I’ll create the “strategy_yolo_buy” contract, define an interface (which would contain a function to place a YOLO bid and some other getter functions ). The contract storage will be used to track necessary values like NFT ID, buyer address, amount e.t.c., contract event will include events for successful YOLO bid, failed YOLO bid e.t.c. 
- I’ll implement logic to handle a situation where the NFT gets purchased mid roll and it is a win (This will probably just cancel the placed yolo bid and maybe emit an event, we can further discuss how to handle this).
- I will be using Pragrma VRF to generate randomness within 1 -75. (i.e Percentage chance with 75% max odds). 
- I’ll write a robust test to ensure the contract behaves as expected.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am front end developer with 6 years experience. 
i have worked with microsoft on several projects,
this will be my first time contributing to the ecosystem and i am ready to work


### How I plan on tackling this issue
Understanding the Requirements:
Carefully review the provided documentation on the YOLO Buy feature from Tensor Trade.
Identify the key components and flow of the feature, including the commit-reveal scheme, the Verifiable Random Function (VRF), and the overall interaction between the user and the contract.
Designing the User Interface:
Create a user-friendly interface that allows users to interact with the YOLO Buy feature.
This may include:
A section to display the available NFTs eligible for YOLO Buy.
A form for users to input their bid amount and initiate the YOLO Buy process.
A section to display the user's YOLO Buy history and track their progress towards free spins.
Appropriate feedback and notifications to the user during the various stages of the YOLO Buy process.
Integrating with the Cairo Contract:
Establish a communication channel between the frontend and the Cairo contract implementing the YOLO Buy feature.
This may involve creating a client-side library or using an existing Cairo SDK to interact with the contract.
Implement the necessary functions to initiate the YOLO Buy process, including the commit and reveal phases.
Handle the response from the contract and update the user interface accordingly.
Handling Edge Cases and Error Handling:
Anticipate and handle various edge cases, such as failed transactions, invalid inputs, or unexpected contract behavior.
Provide clear error messages and feedback to the user to ensure a smooth user experience.
Testing and Validation:
Thoroughly test the YOLO Buy feature, both in isolation and in the context of the overall application.
Validate the user interface, the communication with the Cairo contract, and the overall functionality of the feature.
Optimization and Performance Considerations:
Ensure the YOLO Buy feature is optimized for performance, particularly in areas like rendering, data fetching, and user interactions.
Explore ways to enhance the user experience, such as providing real-time updates or implementing progressive loading techniques.
Documentation and Maintenance:
Document the implementation details, including the integration with the Cairo contract and any custom libraries or components developed.
Ensure the code is well-structured and maintainable, following best practices for frontend development.
Provide clear instructions and guidelines for future developers who may need to work on or extend the YOLO Buy feature.

**Comment by kfastov** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I've wrote several Cairo contracts before, both from scratch and porting code from Solidity. I am aware of the latest Cairo updates, so I can write the up-to-date code.

### How I plan on tackling this issue
At first I would familiarize myself with how the other strategies are implemented (if any), meaning that I'll know what common contracts or data types are available.
Then I'll create a new contract if needed, or modify an existing interface with adding the new possible strategy, implementing this strategy logic.
Then I'll integrate this strategy into existing logic, adding new enum variants or data types in needed.
I think I can do it alone in 7-10 days

**Comment by 0xandee** [comment]
Hi how's it going @kfastov !

**Comment by kfastov** [comment]
Hi @0xandee !
Being a little slow due to weekend.
I looked through the sources, and now thinking of the best way of adding the YOLO buy strategy.
I see it differs from other strategies because it requires at least two steps (commit and reveal).
I wonder if I can perform the reveal phase inside the `canExecuteTakerBid` method, providing revealed random number via some kind of extra params (maybe adding `extra_params` to that method as in `canExecuteTakerAsk`) but still thinking of a more elegant way of doing it.

**Comment by 0xandee** [comment]
> Hi @0xandee ! Being a little slow due to weekend. I looked through the sources, and now thinking of the best way of adding the YOLO buy strategy. I see it differs from other strategies because it requires at least two steps (commit and reveal). I wonder if I can perform the reveal phase inside the `canExecuteTakerBid` method, providing revealed random number via some kind of extra params (maybe adding `extra_params` to that method as in `canExecuteTakerAsk`) but still thinking of a more elegant way of doing it.

Idea of using `extra_params` in `canExecuteTakerBid` is viable, but creating a dedicated reveal function could provide a cleaner approach and it separates the concerns of revealing a commitment and executing a bid.

**Comment by 0xandee** [comment]
@kfastov how is it going bro

**Comment by kfastov** [comment]
@0xandee I plan to push the draft today

**Comment by kfastov** [comment]
Hi @0xandee ,

I wasn't able to meet the deadline due to a poor time estimate, but I'm willing to continue working outside of the ODHack. Here's my current progress:

- Developed a general scheme using Pragma VRF
- Drafted the strategy implementation
- Added lines to the deploy script to deploy this strategy

Next steps:

- Write an integration test using snforge to determine what's working and what still needs to be done
- Complete the implementation
