### ISSUE TITLE
feat: Implement strategy_private_sale contract

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#84]
This strategy only allow specified addresses to buy a listed NFT item.

Read more on `README`, `marketplace/deployment.ts` and `strategy_standard_sale_for_fixed_price.cairo` for references and to understand more how strategy works with marketplace contract.

**Comment by ooochoche** [comment]
Hi

**Comment by od-hunter** [comment]
U

**Comment by ooochoche** [comment]
@0xandee I’m available to work on this

**Comment by ShantelPeters** [comment]
Hi @0xandee can I work on this ?

**Comment by kateberryd** [comment]
Can I work on this please

**Comment by MPSxDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Lately, I've deeply immersed myself in Cairo and Starknet, dedicating significant time to mastering these technologies. Through bootcamps, ongoing training, and recent hackathons, I've built a strong foundation, applied my skills to innovative solutions, and sharpened my problem-solving abilities in the evolving blockchain ecosystem.
I have full availability to develop this issue

### How I plan on tackling this issue
To fully grasp the integration:

1. Review README for an overview.
2. Study marketplace/deployment.ts.
3. Analyze strategy_standard_sale_for_fixed_price.cairo.
4. Understand strategy-marketplace contract interaction.
5. Implement until the desired outcome is achieved.

**Comment by mubarak23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
am a Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.

My recent work with cairo starknet
- https://github.com/horuslabsio/TBA/pull/45
- https://github.com/horuslabsio/karst-core/pull/60
- https://github.com/keep-starknet-strange/art-peace/pull/121
- https://github.com/dojoengine/dojo/pull/1912
- https://github.com/keep-starknet-strange/art-peace/pull/32
- https://github.com/BlockheaderWeb3-Community/dauction-starknet/pull/4


### How I plan on tackling this issue
i intent to solve this issue via the following flow

The main logic will involve validating the buyer's address against a pre-approved list stored in the contract before allowing the transaction to proceed.

the following functions will be implemented

- approved_buyers: A list or mapping of addresses that are allowed to participate in the sale.
- protocol_fee: The fee associated with the sale.
- update protocol_fee: The fee associated with the sale.
 - ownable: To manage contract ownership.
- upgradable: To support contract upgrades.

Address Validation:
Ensure that the can_execute_taker_ask and can_execute_taker_bid functions include logic to check if the buyer’s address is in the approved_buyers list before proceeding with the sale.

Ownership and Upgradability:
Leverage the OwnableComponent and UpgradeableComponent to manage contract ownership and allow for future upgrades

**Comment by bloomingpeach** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hi, I am familiar with Cairo and smart contract development in general, I believe it would help me tackle this issue. 

### How I plan on tackling this issue
First, I will study the `README` and `marketplace/scripts/deployment.ts` to understand the flow and relation between these contracts to properly implement new contract.
After that, I will research the `strategy_standard_sale_for_fixed_price.cairo` file for understanding the codebase, and will follow the code convention. 

When I am done researching, I will work on implementing the contract and make sure to include unit tests with high coverage to ensure correct functionality.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community🇷.

### How I plan on tackling this issue
### 1. Create the `strategy_private_sale` Contract
I would write the `strategy_private_sale` contract, which will be a modification of the `strategy_standard_sale_for_fixed_price` contract. The key difference will be that it restricts sales to a specified list of addresses.

#### Contract Structure
- **Constructor:** Should include a parameter for the list of allowed addresses.
- **Validation Function:** Before executing a sale, check if the buyer's address is in the allowed list.
- **Functions:**
  - `add_allowed_address(address)`: Add a new address to the allowed list.
  - `remove_allowed_address(address)`: Remove an address from the allowed list.
  - `is_address_allowed(address)`: Check if an address is allowed.

### 2. Deploy the `strategy_private_sale` Contract
After writing the contract, I would need to modify the deployment script (`deployment.ts`) to include the deployment of this new strategy.

### 3. Update Deployment Script
In `deployment.ts`,
- **Add Deployment of `StrategyPrivateSale`:**

  I will update the deployment script by including steps similar to the deployment of `StrategyStandardSaleForFixedPrice` and ensure I declare and deploy the `strategy_private_sale` contract, and whitelist it in the `ExecutionManager`.

```typescript
console.log("\n📦 Deploying StrategyPrivateSale...")
const compiledStrategyPrivateSaleCasm = json.parse(fs.readFileSync("../target/dev/flex_StrategyPrivateSale.compiled_contract_class.json").toString("ascii"))
const compiledStrategyPrivateSaleSierra = json.parse(fs.readFileSync("../target/dev/flex_StrategyPrivateSale.contract_class.json").toString("ascii"))
const strategyPrivateSaleCallData: CallData = new CallData(compiledStrategyPrivateSaleSierra.abi)
const strategyPrivateSaleConstructor: Calldata = strategyPrivateSaleCallData.compile("constructor", { allowed_addresses: ["0xYourAllowedAddressHere"], owner: account0.address })
const deployStrategyPrivateSaleResponse = await account0.declareAndDeploy({
    contract: compiledStrategyPrivateSaleSierra,
    casm: compiledStrategyPrivateSaleCasm,
    constructorCalldata: strategyPrivateSaleConstructor
})
console.log("✅ StrategyPrivateSale Deployed: ", deployStrategyPrivateSaleResponse.deploy.contract_address)

console.log("\n📦 Whitelist StrategyPrivateSale...")
const strategyPrivateSaleCall = executionManagerContract.populate("add_strategy", [deployStrategyPrivateSaleResponse.deploy.contract_address])
const add_strategy_private_tx = await executionManagerContract.add_strategy(strategyPrivateSaleCall.calldata)
await provider.waitForTransaction(add_strategy_private_tx.transaction_hash)
console.log("✅ StrategyPrivateSale whitelisted.")
```

### 4. Update the README and Documentation
Add documentation about the new `strategy_private_sale` contract in the README file. Will explain how the contract works, its purpose, and how to deploy and integrate it within the marketplace.

### 5. Test the Contract
Once deployed, I will write and execute tests to ensure the `strategy_private_sale` contract works as expected and make sure only the specified addresses can purchase the listed NFTs.

**Comment by jrmncos** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
hey team! I'm a Software Engineer Backend SSR. I have some experience with Cairo, mainly with on-chain games but I can do this.

### How I plan on tackling this issue
I will follow the strategy suggested and ask if there is any other doubt

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
My frontend development experience enables me to integrate and customize features effectively. I can leverage this to implement and test the address-restricted purchase strategy for NFTs within the marketplace.

### How I plan on tackling this issue
1. **Review Documentation**: Understand current implementation by reading `README`, `deployment.ts`, and `strategy_standard_sale_for_fixed_price.cairo`.
2. **Design Access Control**: Implement logic to restrict NFT purchases to specified addresses.
3. **Update Contracts**: Modify or create contracts to enforce the new purchase restrictions.
4. **Test Thoroughly**: Ensure the restrictions work as expected and test all scenarios.

**Comment by DIWAKARKASHYAP** [comment]
https://diwakar-portfolio.vercel.app/  i want to work on this issue
