### ISSUE TITLE
feat: Whitelist NFT collections or addresses to enable zero trading protocol fee. 

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#86]
Currently, our protocol fee is fixed. I want to make it more flexible by allowing the marketplace owner to whitelist specific NFT collections or addresses, enabling/disabling zero trading protocol fees for those. Take a look at `README` to understand more of how marketplace works.

**Comment by Iwueseiter** [comment]
Hi

**Comment by martinvibes** [comment]
can i be assigned

**Comment by raizo07** [comment]
@0xandee would like to work on this

**Comment by ShantelPeters** [comment]
Can I work on this

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hey, I am ikem Peter. a fullstack software developer with 3+ years of working experience, I would love to help out with this issue...

**Comment by Josh-121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Software engineering background with great experience in smart contract development with experience working on similar projects in previous odhacks(https://app.onlydust.com/u/Josh-121) looking forward to make a first contribution here

### How I plan on tackling this issue
Having gone through the readme & flow charts as required I have a good understanding on how to go about this and would make the required changes. I am sure to take note of any feedbacks and respond swiftly

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a web3 developer
i have experiences with cairo issues

### How I plan on tackling this issue
1. **Implement Whitelist Functionality**: Add functionality to allow the marketplace owner to whitelist specific NFT collections or addresses. This will enable or disable zero trading protocol fees for those whitelisted entities.

2. **Update Protocol Fee Logic**: Modify the fee calculation logic to check if a trade involves a whitelisted collection or address, applying a zero protocol fee if applicable.

3. **Adjust and Document**: Ensure the README and related documentation reflect these changes, providing clear instructions on how to manage the whitelist and understand the new fee structure.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am front end developer with 6 years experience. 
i have worked with microsoft on several projects,
this will be my first time contributing to the hackathon and i am ready to work


### How I plan on tackling this issue
I would approach this issue with following steps
Understand the Current Marketplace Implementation:
Review the existing documentation in the README.md file to understand how the marketplace contract currently works, including the details of the protocol fee.
Identify the areas in the contract where the protocol fee is currently implemented and defined.
Design the New Fee Mechanism:
Decide on the new fee mechanism that will allow the marketplace owner to whitelist specific NFT collections or addresses.
Determine the data structures and mappings needed to keep track of the whitelisted entities and their fee settings.
Consider the different scenarios that need to be handled, such as adding/removing entities from the whitelist, changing the fee settings, and handling the protocol fee calculation based on the whitelist.
Implement the New Fee Mechanism:
Modify the existing protocol fee logic in the marketplace contract to incorporate the new whitelisting and fee-setting functionality.
Add new functions or modifiers to the contract that will allow the marketplace owner to manage the whitelist and configure the fee settings for each whitelisted entity.
Ensure that the protocol fee calculation takes into account the whitelist and the fee settings for the specific NFT collection or address involved in the transaction.
Implement appropriate access control mechanisms to ensure that only the marketplace owner can manage the whitelist and fee settings.
Update the Contract Documentation:
Modify the README.md file to describe the new fee mechanism in detail, including the following:
An overview of the whitelisting and fee-setting functionality.
A description of the new contract functions and their usage.
Examples of how the marketplace owner can manage the whitelist and configure the fee settings.
Considerations and potential edge cases that users should be aware of.
Test and Validate the New Fee Mechanism:
Thoroughly test the new fee mechanism, including various scenarios such as:
Adding and removing entities from the whitelist.
Changing the fee settings for whitelisted entities.
Executing trades with and without the whitelisted entities.
Handling edge cases and error conditions.
Ensure that the protocol fee calculation works as expected and that the new functionality does not introduce any unintended consequences or vulnerabilities.
Deploy and Communicate the Changes:
Once the new fee mechanism is thoroughly tested and validated, deploy the updated marketplace contract to the production environment.
Communicate the changes to the marketplace users, including the new whitelist and fee-setting functionality, and any necessary steps they need to take to adapt to the new system.
Provide clear instructions and examples to help users understand how to interact with the updated marketplace contract.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
As a frontend developer, I have experience in developing and customizing features, including adjusting configurations and implementing user-specific controls. This background allows me to effectively add flexibility to the marketplace by enabling or disabling protocol fees based on whitelisted NFT collections or addresses. My skills in coding and understanding of system integrations will ensure that this feature is seamlessly implemented and user-friendly.

### How I plan on tackling this issue
To make the protocol fee flexible:

1. **Review the README**: Understand the current fee implementation and how it integrates with the marketplace.
2. **Design Whitelisting Mechanism**: Add functionality to whitelist specific NFT collections or addresses. This will involve creating a mapping or list to store whitelisted entries.
3. **Modify Fee Logic**: Update the fee calculation logic to check if the trading address or NFT collection is whitelisted. If so, apply zero trading fees.
4. **Implement and Test**: Develop the changes, test thoroughly to ensure correct functionality, and update the documentation to reflect the new feature.

**Comment by jrmncos** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a Software Enginer Backend SSR. I have more than +5 experiences with web2, but I can understand the logic of this issue and tackle it. Also I have experience with Cairo because I participated in some hackathons.

### How I plan on tackling this issue
I will take a look to the repo to understand the current logic about fixed fee. Then I will create the required components to implement the feature. Of course I will ask for help, but to propose the entire solution I need to dedicate more time. I would really like to work on this ticket.

**Comment by DIWAKARKASHYAP** [comment]
https://diwakar-portfolio.vercel.app/  i want to work on this issue
