### ISSUE TITLE
doc: Improve README of openedition contracts

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#88]
Improve `README.md` by write documentation of `openedition` contracts. The more details the better. 

Tasks:
- [ ] `openedition`

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
i am a web3/ technical writer

**Comment by Iwueseiter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a smart contract developer

**Comment by DIWAKARKASHYAP** [comment]
https://diwakar-portfolio.vercel.app/  i want to work on this issue
