### ISSUE TITLE
doc: Improve README of stakingpool contracts

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#89]
Improve `README.md` by write documentation of `stakingpool` contracts. The more details the better. 

Tasks:
- [ ] `stakingpool`

**Comment by od-hunter** [comment]
Can I do this please?

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a technical writer

### How I plan on tackling this issue
How I plan on tackling this issue
I can handle the MARKETPLACE or STAKING POOL If I am being assign
I have a similar doc https://www.canva.com/design/DAGL_f-YQFI/OvylvJASq1yvUyYs_Gsk9g/view?utm_content=DAGL_f-YQFI&utm_campaign=designshare&utm_medium=link&utm_source=editor you can go through it

I have written a lot of merged documentation on OnlyDust
here is my profile https://app.onlydust.com/u/Gift-Naomi
