### ISSUE TITLE
Implement Functions' Body RoyaltyFeeRegistry contract

### ISSUE THREAD

**Issue by ametel01** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#9]
Implement the functions' body for the [RoyaltyFeeRegistry](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/flex_marketplace/src/marketplace/royalty_fee_registry.cairo) contract. For reference and consistency, the implementation should align with the existing Cairo0 [`RoyaltyFeeRegistry.cairo`](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/blob/main/contracts/marketplace/RoyaltyFeeRegistry.cairo) contract.

Dependencies:

scarb v2.4.0
snforge 0.13.0

Requirements:

Ensure that the code passes both `scarb fmt` and `scarb build` commands without errors, ensuring proper formatting and successful build.

**Comment by VictorONN** [comment]
I can do this

**Comment by and1vo** [comment]
> I can do this

Assigning this to you @VictorONN ~

**Comment by 0xandee** [comment]
Hi how's going @VictorONN

**Comment by and1vo** [comment]
I'll keep this open as well for anyone feel free to assign!

**Comment by ametel01** [comment]
happy to take this
